" Plugins
call plug#begin('~/.vim/plugged')
Plug 'morhetz/gruvbox'
call plug#end()


" indent
set backspace=indent,eol,start
set autoindent 
set smartindent
filetype plugin indent on


" backup
set noswapfile
set undodir=~/.vim/undodir
set undofile
set hidden

" search
set path=.,**
set incsearch

" theme
syntax on
set relativenumber
set number
colorscheme gruvbox
set bg=dark
set splitbelow
set cc=100
set nowrap
set hlsearch
"env variables:
let $RC="$HOME/.vim/vimrc"

